# iOS CircleCI 2.0 configuration file
# https://circleci.com/docs/configuration-reference/
#
# For XCode build version available
# https://circleci.com/docs/using-macos/
#
version: 2.1
jobs:
  build:
    macos:
      xcode: "16.4.0"
    steps:
      - checkout
      - run:
          name: Build Reach5Google (SPM)
          command: xcodebuild build -scheme Reach5Google -destination 'generic/platform=iOS'

default_workflows_tags: &default_workflows_tags
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          <<: *default_workflows_tags
